### ISSUE TITLE
[Meta] Play with Docksal

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#841]
Launch a platform similar to [Play with Docker](http://play-with-docker.com) (could very much be based on it) for Docksal.

It can then be used directly (or cloned) to launch play-platforms for Drupal, Wordpress, etc.

- [x] Web based IDE - https://docs.docksal.io/tools/cloud9/
- [ ] Nicer shell (for beginners) - #274
- [ ] Simple web UI to launch an environment
- [ ] User registration/authentication
- [ ] Kubernetes (cluster) support
- [ ] Resource monitoring and limits (including "out-of-capacity" shorting)
- [ ] Hosting (where, cost, sponsors)
